### ISSUE TITLE
Crash : The end (TEMPORARY Fix inside!)

### ISSUE THREAD

**Issue by Besleh** [Murdy007/Wizzy#10]
endtering the end portal crashes the game 

http://pastebin.com/0Viv2KtC

**Comment by Besleh** [comment]
http://chocolatequest.wikia.com/wiki/Thread:3749

**Comment by Besleh** [comment]
fix :
So in order to workaround this whilst Chocolatin gets around to making a fix, simply copy the snowCastles folder inside Building to the Chocolate folder, so the path becomes config\Chocolate\snowCastles, this will allow the game to start up and you to get into it without crashing.

**Comment by Murdy007** [comment]
I will add those changes to the config for the next version. Chocolatecraft is very buggy and it may be fixed in a new version if there is one, if it is not shown in the next version I will add those config changes. Thankyou. Reply again if you find a more permanent fix but that config change should do for now.
